Added debug print in CI

diff --git a/.forgejo/workflows/build.yml b/.forgejo/workflows/build.yml
--- a/.forgejo/workflows/build.yml
+++ b/.forgejo/workflows/build.yml
@@ -13,23 +13,22 @@ jobs:
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
     steps:
+      - name: Check Docker environment
+        run: |
+          echo "== Environment variable DOCKER_HOST =="
+          echo "${DOCKER_HOST:-<not set>}"
+
+          echo
+          echo "== Check if /var/run/docker.sock exists =="
+          ls -l /var/run/docker.sock || echo "❌ Socket not found"
+
+          echo
+          echo "== Check Docker daemon connectivity =="
+          docker version || echo "❌ Docker daemon not reachable"
+
       - name: Clone repository
         run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .
 
       - name: Build docker image
         run: docker build -t glados:latest .
 
-      # - name: Install node for upload Artifact
-      #   run: apt update && apt install nodejs -y
-
-      # - name: Upload final jar artifact
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: GLaDOS
-      #     path: target/GLaDOS-2.0.0.jar
-
-      # - name: Upload items artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: items
-      #     path: items/*
